matrix:
  include:
    - language: python
      install:
        - pip install --upgrade pip
        - pip install -U -r python/requirements.txt dask[dataframe] distributed
      before_script:
        - cd python
      script:
        - pytest tests
    - language: r
      before_script:
        - cd R
      script:
        - R CMD build .
        - R CMD check *tar.gz
